version: "3"
services:
  node-app:
    build: ./app
    container_name: node-app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.23-rc0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
