version: "3"
services:
  mongo:
    image: mongo:4.4.23-rc0
    container_name: mongodb
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
volumes:
  mongodb_data:
